language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lsmin01/react-test-app -f ./frontend/Dockerfile.dev ./frontend    

script:
    - docker run -e CI=true lsmin01/react-test-app npm run test

after_success:
    - docker build -t lsmin01/docker-frontend ./frontend
    - docker build -t lsmin01/docker-backend ./backend
    - docker build -t lsmin01/docker-nginx ./nginx
    
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push lsmin01/docker-frontend
    - docker push lsmin01/docker-backend
    - docker push lsmin01/docker-nginx

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-fullstack-a[["
    env: DockerFullstackA-env
    bucket_name: elasticbeanstalk-ap-northeast-2-067375555374
    bucket_path: "docker-fullstack-a[["
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET